### ISSUE TITLE
An requirements.txt file might needed

### ISSUE THREAD

**Issue by rovo98** [Adj325/BlogCrawlers#2]
IIUC, we might often use vitrual env to manage different project deps since it's more controlable.

And I think it will be better to provide an requirements.txt file to clearify python project's deps (So that users can set up environment quickly and correctly)

To generate an requirements.txt file for one project, we can using ``pip freeze > requirements.txt`` (In the context of project's virtual env)

**Comment by dcLunatic** [comment]
Waiting @Adj325 to pass my pr that add the requiements file.
BTW, I recomment the use pipreqs for generating requirements file.
